# Generated by Django 2.1.5 on 2019-04-02 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190313_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='charge',
            field=models.ForeignKey(on_delete=models.SET('Null'), to=settings.AUTH_USER_MODEL),
        ),
    ]
