# Generated by Django 2.1.5 on 2019-02-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rolemenu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolemenu',
            name='order',
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
