# Generated by Django 2.1.5 on 2019-02-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190226_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
