# Generated by Django 2.1.7 on 2019-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190226_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default='#', max_length=32),
            preserve_default=False,
        ),
    ]
