# Generated by Django 2.1.5 on 2019-03-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='no',
            field=models.CharField(default='2', max_length=32),
            preserve_default=False,
        ),
    ]
