# Generated by Django 2.1.5 on 2019-03-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0003_auto_20190328_1505'),
        ('testcase', '0002_testcase_no'),
    ]

    operations = [
    ]
