# Generated by Django 2.1.5 on 2019-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0005_auto_20190402_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
