# Generated by Django 2.1.5 on 2019-02-22 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190221_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='normal', max_length=10)),
                ('aceess', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('upassword', models.CharField(max_length=64)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Role')),
            ],
        ),
    ]
