# Generated by Django 2.1.5 on 2019-04-03 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testcase', '0006_auto_20190403_1458'),
        ('datasource', '0006_auto_20190403_1111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ds_range', models.CharField(blank=True, max_length=72, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('case_id', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='testcase.TestCase')),
                ('charge', models.ForeignKey(on_delete=models.SET('Null'), to=settings.AUTH_USER_MODEL)),
                ('ds_id', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='datasource.Datasource')),
            ],
        ),
        migrations.CreateModel(
            name='TP_Run_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_order', models.IntegerField()),
                ('beg_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TP_Run_His',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beg_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('log_path', models.CharField(blank=True, max_length=72, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('case_id', models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), to='testcase.TestCase')),
                ('tp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testplan.TestPlan')),
            ],
        ),
        migrations.AddField(
            model_name='tp_run_detail',
            name='his_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testplan.TP_Run_His'),
        ),
    ]
