# Generated by Django 2.1.5 on 2019-04-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190402_1710'),
        ('testplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.Projects'),
            preserve_default=False,
        ),
    ]
