# Generated by Django 2.1.5 on 2019-04-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplan', '0002_testplan_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testplan',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='testplan',
            old_name='ds_id',
            new_name='ds',
        ),
        migrations.RenameField(
            model_name='tp_run_detail',
            old_name='his_id',
            new_name='his',
        ),
        migrations.RenameField(
            model_name='tp_run_his',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='tp_run_his',
            old_name='tp_id',
            new_name='testplan',
        ),
    ]
