# Generated by Django 2.1.5 on 2019-03-28 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20190313_1534'),
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='charge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
            preserve_default=False,
        ),
    ]
