# Generated by Django 2.1.5 on 2019-03-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_auto_20190328_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='no',
            field=models.CharField(default='1', max_length=32),
            preserve_default=False,
        ),
    ]
