# Generated by Django 2.1.5 on 2019-03-29 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_auto_20190328_1501'),
        ('datasource', '0003_datasource_no'),
    ]

    operations = [
    ]
