# Generated by Django 2.1.5 on 2019-04-02 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_merge_20190329_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasource',
            name='charge',
            field=models.ForeignKey(on_delete=models.SET('Null'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Projects'),
        ),
    ]
